//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDelItla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudianteAsignatura
    {
        public int id { get; set; }
        public Nullable<int> idEstudiante { get; set; }
        public Nullable<int> idAsignatura { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual Estudiante Estudiante { get; set; }
    }
}
